Update

diff --git a/patch/sbin/install-pve b/patch/sbin/install-pve
--- a/patch/sbin/install-pve
+++ b/patch/sbin/install-pve
@@ -3,8 +3,8 @@
 # ==============================================================================
 #  脚本名称：install-pve
 #  适用架构：ARM64 (aarch64/arm64)
-#  脚本功能：Armbian ARM64 系统安装 Pxvirt (Proxmox VE)
-#  适用系统：Debian 12 (bookworm) -> Pxvirt 8 | Debian 13 (trixie) -> Pxvirt 9
+#  脚本功能：Armbian ARM64 系统安装 Pxvirt or Proxmox VE
+#  适用系统：Debian 12 (bookworm) -> Pxvirt 8 | Debian 13 (trixie) -> PVE 9
 #  功能说明：配置国内源、添加 Pxvirt 源、内存占用优化、配置网络与 IPv6 参数
 #  教程链接：https://zhou.pp.ua
 # ==============================================================================
@@ -17,6 +17,7 @@ readonly SUCCESS="[\033[92m 成功 \033[0m]"
 readonly OPTIONS="[\033[93m 选项 \033[0m]"
 readonly ERROR="[\033[91m 错误 \033[0m]"
 readonly SN="[\033[96m 序号 \033[0m]"
+readonly SOURCE_MARK="# Generated by install-pve"
 
 ADDR_INFO=""
 ARCH=""
@@ -363,6 +364,7 @@ setup_repositories() {
     fi
 
     cat > "${source_file}" <<EOF
+${SOURCE_MARK}
 Types: deb
 URIs: ${mirror}/pxcloud/pxvirt
 Suites: ${VERSION_CODENAME}
@@ -371,6 +373,70 @@ Signed-By: ${keyring}
 EOF
     [[ $? -eq 0 ]] || error "写入 pxvirt.sources 失败！"
     echo -e "${STEPS} 已写入：\033[95m${source_file}\033[0m"
+}
+
+setup_repositories_new() {
+    local keyring="/usr/share/keyrings/pve-repo.gpg"
+    local mirror="https://pve.zhou.pp.ua"
+    local old_source_file="/etc/apt/sources.list.d/pxvirt-sources.list"
+    local old_source_backup_file="/etc/apt/sources.list.d/pxvirt-sources.list.bak"
+    local old_source_deb822_file="/etc/apt/sources.list.d/pxvirt.sources"
+    local old_local_source_file="/etc/apt/sources.list.d/pve-arm64-local.list"
+    local source_file="/etc/apt/sources.list.d/pve-arm64.sources"
+
+    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+
+    echo -e "${INFO} 使用 PVE ARM64 软件源：\033[95m${mirror}\033[0m"
+
+    if download_file "${keyring}" "${mirror}/pve-repo.gpg"; then
+        echo -e "${STEPS} 已下载：\033[95m${keyring}\033[0m"
+    else
+        error "下载 pve-repo.gpg 失败！"
+    fi
+
+    if [[ -f "${old_source_file}" ]]; then
+        [[ -f "${old_source_backup_file}" ]] ||
+            cp -f "${old_source_file}" "${old_source_backup_file}" || error "备份旧格式 Pxvirt 源失败！"
+        rm -f "${old_source_file}" || error "删除旧格式 Pxvirt 源失败！"
+    fi
+
+    rm -f "${old_source_deb822_file}" "${old_local_source_file}" || true
+
+    cat > "${source_file}" <<EOF
+${SOURCE_MARK}
+Types: deb
+URIs: ${mirror}/arm64
+Suites: ${VERSION_CODENAME}
+Components: main
+Signed-By: ${keyring}
+EOF
+    [[ $? -eq 0 ]] || error "写入 pve-arm64.sources 失败！"
+    echo -e "${STEPS} 已写入：\033[95m${source_file}\033[0m"
+}
+
+repositories_select() {
+    while true; do
+        echo -e "${INFO} 请选择版本："
+		echo -e "${SN} [\033[96m 1 \033[0m] -> Proxmox VE 9 [\033[92m 源码编译版 \033[0m]"
+		echo -e "${SN} [\033[96m 2 \033[0m] -> Proxmox VE 9 [\033[92m 定制版 by lierfang \033[0m]"
+        read -r -p "$(echo -e "${OPTIONS} 请输入 [\033[92m 1-2 \033[0m] [ 回车默认 \033[92m1\033[0m ]：" )" select_choice
+
+        select_choice="${select_choice:-1}"
+
+        case "${select_choice}" in
+            1)
+                setup_repositories_new
+                break 
+                ;;
+            2)
+                setup_repositories
+                break
+                ;;
+            *)
+                echo -e "${ERROR} 输入错误，请重新选择！"
+                ;;
+        esac
+    done
 }
 
 setup_networking() {
@@ -439,7 +505,7 @@ EOF
     [[ $? -eq 0 ]] || error "写入 /etc/hosts 失败！"
 }
 
-pxvirt_major_version() {
+pve_major_version() {
     if [[ "${VERSION_CODENAME}" == "bookworm" ]]; then
         echo 8
     else
@@ -450,8 +516,8 @@ pxvirt_major_version() {
 install_pve() {
     local pxvirt_version
 
-    pxvirt_version=$(pxvirt_major_version)
-    echo -e "${INFO} 安装 Pxvirt ${pxvirt_version}..."
+    pve_version=$(pve_major_version)
+    echo -e "${INFO} 安装 Proxmox VE ${pve_version}..."
 
     if apt-get update && apt-get install -y proxmox-ve; then
         if [[ -f /etc/ophub-release ]]; then
@@ -462,9 +528,9 @@ install_pve() {
             systemctl restart pveproxy >/dev/null 2>&1 || error "无法重启 pveproxy 服务，请检查！"
             echo -e "${SUCCESS} 证书更新成功！"
         fi
-        echo -e "${SUCCESS} Pxvirt ${pxvirt_version} 安装成功！请重启设备后浏览器访问：[\033[92m https://${IP_ADDR}:8006 \033[0m]"
+        echo -e "${SUCCESS} Proxmox VE ${pve_version} 安装成功！请重启设备后浏览器访问：[\033[92m https://${IP_ADDR}:8006 \033[0m]"
     else
-        error "Pxvirt ${pxvirt_version} 安装失败，请检查源和网络！"
+        error "Proxmox VE ${pve_version} 安装失败，请检查源和网络！"
     fi
 }
 
@@ -631,7 +697,11 @@ main() {
     detect_network_info
     confirm_source
     backup_and_comment_sources
-    setup_repositories
+    if [[ "${VERSION_CODENAME}" == "trixie" ]]; then
+        repositories_select
+    else
+        setup_repositories
+    fi
     setup_networking
     set_hostname
     configure_network
