Update

diff --git a/.github/workflows/Build-Armbian.yml b/.github/workflows/Build-Armbian.yml
--- a/.github/workflows/Build-Armbian.yml
+++ b/.github/workflows/Build-Armbian.yml
@@ -150,7 +150,6 @@ jobs:
         run: |
           "${GITHUB_WORKSPACE}/scripts/apply_patches.sh"
           "${GITHUB_WORKSPACE}/scripts/rename_to_conf.sh"
-          ls -la
 
       - name: Compile Armbian [ ${{ inputs.BOARD }} ${{ inputs.BRANCH }} ${{ inputs.RELEASE }} ]
         working-directory: /mnt/workdir/build
@@ -245,6 +244,7 @@ jobs:
               base_name=$(echo "${f}" | sed -E 's/_.*//')
               newf="${base_name}-${{ env.KERNEL_VERSION }}.deb"
               if [ "${f}" != "${newf}" ]; then
+                echo "Renaming: ${f} → ${newf}"
                 mv "${f}" "${newf}"
               fi
               renamed_files+=("${newf}")
@@ -256,7 +256,7 @@ jobs:
             ls -1 "/mnt/workdir/build/output/debs"
             exit 1
           fi
-          tar -tzf "../kernel-${{ env.KERNEL_VERSION }}-${{ env.LINUX_FAMILY }}.tar.gz" || { echo "Failed to verify tar.gz file"; exit 1; }
+          tar -tzf "../kernel-${{ env.KERNEL_VERSION }}-${{ env.LINUX_FAMILY }}.tar.gz" > /dev/null || { echo "Failed to verify tar.gz file"; exit 1; }
 
       - name: Upload Kernel to Release
         if: ${{ inputs.UPLOAD_DEB_PACKAGES == 'yes' }}
diff --git a/.github/workflows/Build-Kernel.yml b/.github/workflows/Build-Kernel.yml
--- a/.github/workflows/Build-Kernel.yml
+++ b/.github/workflows/Build-Kernel.yml
@@ -114,7 +114,6 @@ jobs:
         run: |
           "${GITHUB_WORKSPACE}/scripts/apply_patches.sh"
           "${GITHUB_WORKSPACE}/scripts/rename_to_conf.sh"
-          ls -la
 
       - name: Compile Kernel [ ${{ inputs.LinuxFamily }} ${{ inputs.BRANCH }} ]
         working-directory: /mnt/workdir/build
@@ -153,6 +152,7 @@ jobs:
               base_name=$(echo "${f}" | sed -E 's/_.*//')
               newf="${base_name}-${KERNEL_VERSION}.deb"
               if [ "${f}" != "${newf}" ]; then
+                echo "Renaming: ${f} → ${newf}"
                 mv "${f}" "${newf}"
               fi
               renamed_files+=("${newf}")
@@ -164,7 +164,7 @@ jobs:
             ls -1 "/mnt/workdir/build/output/debs"
             exit 1
           fi
-          tar -tzf "../kernel-${KERNEL_VERSION}-${LINUX_FAMILY}.tar.gz" || { echo "Failed to verify tar.gz file"; exit 1; }
+          tar -tzf "../kernel-${KERNEL_VERSION}-${LINUX_FAMILY}.tar.gz" > /dev/null || { echo "Failed to verify tar.gz file"; exit 1; }
 
       - name: Upload Kernel to Release
         uses: ncipollo/release-action@main
diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -119,7 +119,6 @@ jobs:
           cp -f ${GITHUB_WORKSPACE}/patch/X2/rk3566-panther-x2.dts patch/kernel/archive/rockchip64-6.17/dt/
           cp -f ${GITHUB_WORKSPACE}/patch/JP/rk3566-jp-tvbox.dts patch/kernel/archive/rockchip64-6.17/dt/
           cp -f ${GITHUB_WORKSPACE}/patch/test/rockchip64-6.17/* patch/kernel/archive/rockchip64-6.17/
-          ls -la
 
       - name: Compile Kernel [ ${{ inputs.LinuxFamily }} ${{ inputs.BRANCH }} ]
         working-directory: /mnt/workdir/build
@@ -158,6 +157,7 @@ jobs:
               base_name=$(echo "${f}" | sed -E 's/_.*//')
               newf="${base_name}-${KERNEL_VERSION}.deb"
               if [ "${f}" != "${newf}" ]; then
+                echo "Renaming: ${f} → ${newf}"
                 mv "${f}" "${newf}"
               fi
               renamed_files+=("${newf}")
@@ -169,7 +169,7 @@ jobs:
             ls -1 "/mnt/workdir/build/output/debs"
             exit 1
           fi
-          tar -tzf "../kernel-${KERNEL_VERSION}-${LINUX_FAMILY}.tar.gz" || { echo "Failed to verify tar.gz file"; exit 1; }
+          tar -tzf "../kernel-${KERNEL_VERSION}-${LINUX_FAMILY}.tar.gz" > /dev/null || { echo "Failed to verify tar.gz file"; exit 1; }
 
       - name: Upload Kernel to Release
         uses: ncipollo/release-action@main
diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -125,7 +125,6 @@ jobs:
           "${GITHUB_WORKSPACE}/scripts/rename_to_conf.sh"
           sed -i 's|https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git|https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git|' lib/functions/configuration/main-config.sh
           sed -i "s|tag:v6\.18-rc[1-7]|tag:v6\.18-rc${{ inputs.RC_VERSION }}|" config/sources/mainline-kernel.conf.sh
-          ls -la
 
       - name: Compile Kernel [ ${{ inputs.LinuxFamily }} ${{ inputs.BRANCH }} ]
         working-directory: /mnt/workdir/build
@@ -164,6 +163,7 @@ jobs:
               base_name=$(echo "${f}" | sed -E 's/_.*//')
               newf="${base_name}-${KERNEL_VERSION}.deb"
               if [ "${f}" != "${newf}" ]; then
+                echo "Renaming: ${f} → ${newf}"
                 mv "${f}" "${newf}"
               fi
               renamed_files+=("${newf}")
@@ -175,7 +175,7 @@ jobs:
             ls -1 "/mnt/workdir/build/output/debs"
             exit 1
           fi
-          tar -tzf "../kernel-${KERNEL_VERSION}-${LINUX_FAMILY}.tar.gz" || { echo "Failed to verify tar.gz file"; exit 1; }
+          tar -tzf "../kernel-${KERNEL_VERSION}-${LINUX_FAMILY}.tar.gz" > /dev/null || { echo "Failed to verify tar.gz file"; exit 1; }
 
       - name: Upload Kernel to Release
         uses: ncipollo/release-action@main
